// Code generated by the Code CIN AOT builder; DO NOT EDIT.
//
// 这是独立可执行文件的入口 shell: program.ucbc 与 program.mem 由构建器
// 生成并嵌入, 运行时由内置 Go VM 执行 (静态链接, 无需 Python/动态库)。
package main

import (
	_ "embed"
	"os"

	"codecin-native/aot"
)

//go:embed program.ucbc
var bytecode []byte

//go:embed program.mem
var memImage []byte

func main() {
	os.Exit(aot.Main(bytecode, memImage))
}
