// Code generated by script/gen_native_isa.py from codecin/isa.py; DO NOT EDIT.
// 单一事实来源: codecin/isa.py Opcode / Syscall / KIND_* 常量.
// 修改指令集后运行: python script/gen_native_isa.py

package engine

// 操作数种类 (与 isa.py KIND_* 一致)
const kindReg = 0
const kindImm = 1
const kindVec = 2
const kindVecLane = 3
const kindMem = 4
const kindCond = 5
const kindFloat = 6
const kindStr = 7

// 操作码 (与 isa.py Opcode 完整一致; 原生 VM 仅实现子集, 见 vm.go opcodeSupported)
const opMOV = 0
const opLOAD = 1
const opSTORE = 2
const opADD = 3
const opSUB = 4
const opMUL = 5
const opDIV = 6
const opAND = 7
const opOR = 8
const opXOR = 9
const opSHL = 10
const opSHR = 11
const opINC = 12
const opDEC = 13
const opCMP = 14
const opJMP = 15
const opJZ = 16
const opJNZ = 17
const opJE = 18
const opJL = 19
const opJG = 20
const opPUSH = 21
const opPOP = 22
const opCALL = 23
const opRET = 24
const opIN = 25
const opOUT = 26
const opHALT = 27
const opADDS = 28
const opSUBS = 29
const opADDC = 30
const opSUBC = 31
const opLSL = 32
const opLSR = 33
const opASR = 34
const opROR = 35
const opMVN = 36
const opEOR = 37
const opBIC = 38
const opORN = 39
const opLDR = 40
const opSTR = 41
const opLDP = 42
const opSTP = 43
const opCBZ = 44
const opCBNZ = 45
const opTBZ = 46
const opTBNZ = 47
const opB = 48
const opBL = 49
const opBR = 50
const opNOP = 51
const opWFE = 52
const opWFI = 53
const opSEV = 54
const opCSEL = 55
const opCSINC = 56
const opCSINV = 57
const opCSNEG = 58
const opSXTB = 59
const opSXTH = 60
const opSXTW = 61
const opUXTB = 62
const opUXTH = 63
const opCLZ = 64
const opCLS = 65
const opRBIT = 66
const opREV = 67
const opFADD = 68
const opFSUB = 69
const opFMUL = 70
const opFDIV = 71
const opFCMP = 72
const opFCVT = 73
const opFABS = 74
const opFNEG = 75
const opLDRS = 76
const opSTRS = 77
const opVADD = 78
const opVSUB = 79
const opVMUL = 80
const opVDIV = 81
const opVLD1 = 82
const opVST1 = 83
const opLB = 84
const opLH = 85
const opLW = 86
const opLD = 87
const opSB = 88
const opSH = 89
const opSW = 90
const opSD = 91
const opADDI = 92
const opSLTI = 93
const opSLTIU = 94
const opXORI = 95
const opORI = 96
const opANDI = 97
const opSLLI = 98
const opSRLI = 99
const opSRAI = 100
const opBEQ = 101
const opBNE = 102
const opBLT = 103
const opBGE = 104
const opBLTU = 105
const opBGEU = 106
const opJALR = 107
const opJAL = 108
const opLUI = 109
const opAUIPC = 110
const opSYS = 111

// 操作码名 -> 编码 (供 UCBC 编码器使用)
var opcodeByName = map[string]uint8{
	"MOV":   opMOV,
	"LOAD":  opLOAD,
	"STORE": opSTORE,
	"ADD":   opADD,
	"SUB":   opSUB,
	"MUL":   opMUL,
	"DIV":   opDIV,
	"AND":   opAND,
	"OR":    opOR,
	"XOR":   opXOR,
	"SHL":   opSHL,
	"SHR":   opSHR,
	"INC":   opINC,
	"DEC":   opDEC,
	"CMP":   opCMP,
	"JMP":   opJMP,
	"JZ":    opJZ,
	"JNZ":   opJNZ,
	"JE":    opJE,
	"JL":    opJL,
	"JG":    opJG,
	"PUSH":  opPUSH,
	"POP":   opPOP,
	"CALL":  opCALL,
	"RET":   opRET,
	"IN":    opIN,
	"OUT":   opOUT,
	"HALT":  opHALT,
	"ADDS":  opADDS,
	"SUBS":  opSUBS,
	"ADDC":  opADDC,
	"SUBC":  opSUBC,
	"LSL":   opLSL,
	"LSR":   opLSR,
	"ASR":   opASR,
	"ROR":   opROR,
	"MVN":   opMVN,
	"EOR":   opEOR,
	"BIC":   opBIC,
	"ORN":   opORN,
	"LDR":   opLDR,
	"STR":   opSTR,
	"LDP":   opLDP,
	"STP":   opSTP,
	"CBZ":   opCBZ,
	"CBNZ":  opCBNZ,
	"TBZ":   opTBZ,
	"TBNZ":  opTBNZ,
	"B":     opB,
	"BL":    opBL,
	"BR":    opBR,
	"NOP":   opNOP,
	"WFE":   opWFE,
	"WFI":   opWFI,
	"SEV":   opSEV,
	"CSEL":  opCSEL,
	"CSINC": opCSINC,
	"CSINV": opCSINV,
	"CSNEG": opCSNEG,
	"SXTB":  opSXTB,
	"SXTH":  opSXTH,
	"SXTW":  opSXTW,
	"UXTB":  opUXTB,
	"UXTH":  opUXTH,
	"CLZ":   opCLZ,
	"CLS":   opCLS,
	"RBIT":  opRBIT,
	"REV":   opREV,
	"FADD":  opFADD,
	"FSUB":  opFSUB,
	"FMUL":  opFMUL,
	"FDIV":  opFDIV,
	"FCMP":  opFCMP,
	"FCVT":  opFCVT,
	"FABS":  opFABS,
	"FNEG":  opFNEG,
	"LDRS":  opLDRS,
	"STRS":  opSTRS,
	"VADD":  opVADD,
	"VSUB":  opVSUB,
	"VMUL":  opVMUL,
	"VDIV":  opVDIV,
	"VLD1":  opVLD1,
	"VST1":  opVST1,
	"LB":    opLB,
	"LH":    opLH,
	"LW":    opLW,
	"LD":    opLD,
	"SB":    opSB,
	"SH":    opSH,
	"SW":    opSW,
	"SD":    opSD,
	"ADDI":  opADDI,
	"SLTI":  opSLTI,
	"SLTIU": opSLTIU,
	"XORI":  opXORI,
	"ORI":   opORI,
	"ANDI":  opANDI,
	"SLLI":  opSLLI,
	"SRLI":  opSRLI,
	"SRAI":  opSRAI,
	"BEQ":   opBEQ,
	"BNE":   opBNE,
	"BLT":   opBLT,
	"BGE":   opBGE,
	"BLTU":  opBLTU,
	"BGEU":  opBGEU,
	"JALR":  opJALR,
	"JAL":   opJAL,
	"LUI":   opLUI,
	"AUIPC": opAUIPC,
	"SYS":   opSYS,
}

// 每个操作码的参数个数 (-1 表示变长, 不校验);
// 与 isa.py Constants.ARG_COUNTS 一致。原生 VM 用它校验不可信字节码,
// 避免 argc 与操作码不匹配时 execute 里 args[i] 越界 panic。
var argCounts = [112]int16{
	opMOV:   2,
	opLOAD:  2,
	opSTORE: 2,
	opADD:   2,
	opSUB:   2,
	opMUL:   2,
	opDIV:   2,
	opAND:   2,
	opOR:    2,
	opXOR:   2,
	opSHL:   2,
	opSHR:   2,
	opINC:   1,
	opDEC:   1,
	opCMP:   2,
	opJMP:   1,
	opJZ:    1,
	opJNZ:   1,
	opJE:    1,
	opJL:    1,
	opJG:    1,
	opPUSH:  1,
	opPOP:   1,
	opCALL:  1,
	opRET:   0,
	opIN:    1,
	opOUT:   1,
	opHALT:  0,
	opADDS:  3,
	opSUBS:  3,
	opADDC:  3,
	opSUBC:  3,
	opLSL:   3,
	opLSR:   3,
	opASR:   3,
	opROR:   3,
	opMVN:   2,
	opEOR:   3,
	opBIC:   3,
	opORN:   3,
	opLDR:   2,
	opSTR:   2,
	opLDP:   3,
	opSTP:   3,
	opCBZ:   2,
	opCBNZ:  2,
	opTBZ:   3,
	opTBNZ:  3,
	opB:     -1,
	opBL:    1,
	opBR:    1,
	opNOP:   0,
	opWFE:   0,
	opWFI:   0,
	opSEV:   0,
	opCSEL:  4,
	opCSINC: 4,
	opCSINV: 4,
	opCSNEG: 4,
	opSXTB:  2,
	opSXTH:  2,
	opSXTW:  2,
	opUXTB:  2,
	opUXTH:  2,
	opCLZ:   2,
	opCLS:   2,
	opRBIT:  2,
	opREV:   2,
	opFADD:  3,
	opFSUB:  3,
	opFMUL:  3,
	opFDIV:  3,
	opFCMP:  2,
	opFCVT:  2,
	opFABS:  2,
	opFNEG:  2,
	opLDRS:  2,
	opSTRS:  2,
	opVADD:  3,
	opVSUB:  3,
	opVMUL:  3,
	opVDIV:  3,
	opVLD1:  2,
	opVST1:  2,
	opLB:    2,
	opLH:    2,
	opLW:    2,
	opLD:    2,
	opSB:    2,
	opSH:    2,
	opSW:    2,
	opSD:    2,
	opADDI:  3,
	opSLTI:  3,
	opSLTIU: 3,
	opXORI:  3,
	opORI:   3,
	opANDI:  3,
	opSLLI:  3,
	opSRLI:  3,
	opSRAI:  3,
	opBEQ:   3,
	opBNE:   3,
	opBLT:   3,
	opBGE:   3,
	opBLTU:  3,
	opBGEU:  3,
	opJALR:  -1,
	opJAL:   2,
	opLUI:   2,
	opAUIPC: 2,
	opSYS:   -1,
}

// SYS 功能号 (与 isa.py Syscall 一致)
const sysSQRT = 0
const sysPOW = 1
const sysABS = 2
const sysSIN = 3
const sysCOS = 4
const sysTAN = 5
const sysFADD = 6
const sysFSUB = 7
const sysFMUL = 8
const sysFDIV = 9
const sysFCMP = 10
const sysFTOI = 11
const sysITOF = 12
const sysRAND = 13
const sysSRAND = 14
const sysTIME = 15
const sysSTRLEN = 16
const sysSTRCMP = 17
const sysSTRCPY = 18
const sysSTRCAT = 19
const sysMALLOC = 20
const sysPRINTFLO = 21
const sysITOA = 22
const sysFTOA = 23
const sysPRINTSTR = 24
const sysSTRCONCAT = 25
const sysBOOLSTR = 26
const sysABORT = 27
const sysSUBSTR = 28
const sysINDEXOF = 29
const sysTOUPPER = 30
const sysTOLOWER = 31
const sysFLOOR = 32
const sysCEIL = 33
const sysROUND = 34
const sysATOI = 35
const sysTRIM = 36
const sysLTRIM = 37
const sysRTRIM = 38
const sysAUDIOPLAY = 39
const sysAUDIOSTOP = 40
const sysAUDIOVOL = 41
const sysAUDIOWAIT = 42
const sysCANVASNEW = 43
const sysCANVASSET = 44
const sysCANVASRECT = 45
const sysCANVASCIRC = 46
const sysCANVASTEXT = 47
const sysCANVASLINE = 48
const sysCANVASSAVE = 49
const sysCANVASSHOW = 50
const sysFILEREAD = 51
const sysFILEWRITE = 52
const sysFILEAPPEND = 53
const sysFILEEXISTS = 54
const sysFILEDELETE = 55
const sysFILESIZE = 56
const sysMKDIR = 57
const sysDIRLIST = 58
const sysEXEC = 59
const sysEXECOUTPUT = 60
const sysGETENV = 61
const sysSETENV = 62
const sysOSNAME = 63
const sysHOSTNAME = 64
const sysUSERNAME = 65
const sysCWD = 66
const sysHOMEDIR = 67
const sysTERMUXAVAIL = 68
const sysTERMUXNOTIFY = 69
const sysTERMUXTOAST = 70
const sysTERMUXCLIPGET = 71
const sysTERMUXCLIPSET = 72
const sysTERMUXBATTERY = 73
const sysTERMUXVIBRATE = 74
const sysTERMUXTTS = 75
const sysTERMUXLOCATION = 76
const sysTERMUXWIFI = 77
const sysTERMUXDIALOG = 78
const sysTERMUXSMS = 79
