// Code generated by script/gen_native_isa.py from codecin/__init__.py; DO NOT EDIT.
// 单一事实来源: codecin/__init__.py 的 __version__ (见 pyproject.toml dynamic version)。

package engine

// BuildVersion 是 Code CIN 的版本号 (被 codecin_version() 与日志使用)。
const BuildVersion = "5.5.0"
