#!/usr/bin/env python3
"""由 codecin/isa.py 生成 Go 原生库常量文件 (单一事实来源)。

Python (isa.py) 与 Go (native/*.go) 的指令码/操作数类型码/SYS 功能号
必须完全一致。本脚本把 Python 侧作为唯一权威:

    python script/gen_native_isa.py          # 重写 codecin/native/engine/isa_gen.go
                                             #      与 codecin/native/compiler/syscalls.go
    python script/gen_native_isa.py --check  # 校验一致 (CI 使用)

生成后请运行 gofmt (开发环境), 再 go build -buildmode=c-shared 验证。
注意: 当前生成器输出的 Go 源码未经过 gofmt, 直接运行 `gofmt -l` 会报这两个文件;
因此 CI 暂未启用 gofmt 门禁 (见 docs/SUGGESTIONS.md §2.1)。
"""

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from codecin.isa import KIND_FLOAT, KIND_IMM, KIND_MEM, KIND_REG, KIND_STR, \
    KIND_VEC, KIND_VECLANE, KIND_COND, Opcode, Syscall  # noqa: E402

OUT_PATH = os.path.join(ROOT, 'codecin', 'native', 'engine', 'isa_gen.go')
COMPILER_SYS_PATH = os.path.join(ROOT, 'codecin', 'native', 'compiler', 'syscalls.go')

# Python 常量名 -> Go 常量名 (特殊缩写, 与既有 vm.go 用法保持一致)
_KIND_GO_NAMES = {
    KIND_REG: 'kindReg', KIND_IMM: 'kindImm', KIND_VEC: 'kindVec',
    KIND_VECLANE: 'kindVecLane', KIND_MEM: 'kindMem', KIND_COND: 'kindCond',
    KIND_FLOAT: 'kindFloat', KIND_STR: 'kindStr',
}

# Syscall 成员名 -> Go sys 常量名 (与既有用法一致)
_SYS_SPECIAL = {
    'PRINT_FLOAT': 'sysPRINTFLO',
    'PRINT_STR': 'sysPRINTSTR',
    'STR_CONCAT': 'sysSTRCONCAT',
    'BOOL_STR': 'sysBOOLSTR',
}


def sys_id(name: str) -> str:
    return _SYS_SPECIAL.get(name, 'sys' + name)


def build_compiler_sys() -> str:
    """为 Go CIN 编译器生成导出的 SYS 功能号常量 (package compiler)。"""
    lines = []
    lines.append('// Code generated by script/gen_native_isa.py from codecin/isa.py; DO NOT EDIT.')
    lines.append('// 单一事实来源: codecin/isa.py Syscall 常量.')
    lines.append('')
    lines.append('package compiler')
    lines.append('')
    lines.append('// SYS 功能号 (与 isa.py Syscall 一致; 编译器以 SysXXX 引用)。')
    for s in Syscall:
        lines.append(f'const Sys{s.name} = {s.value}')
    lines.append('')
    return '\n'.join(lines)


def build_go() -> str:
    lines = []
    lines.append('// Code generated by script/gen_native_isa.py from codecin/isa.py; DO NOT EDIT.')
    lines.append('// 单一事实来源: codecin/isa.py Opcode / Syscall / KIND_* 常量.')
    lines.append('// 修改指令集后运行: python script/gen_native_isa.py')
    lines.append('')
    lines.append('package engine')
    lines.append('')
    lines.append('// 操作数种类 (与 isa.py KIND_* 一致)')
    for value in sorted(_KIND_GO_NAMES):
        lines.append(f'const {_KIND_GO_NAMES[value]} = {value}')
    lines.append('')
    lines.append('// 操作码 (与 isa.py Opcode 完整一致; 原生 VM 仅实现子集, 见 vm.go opcodeSupported)')
    for m in Opcode:
        lines.append(f'const op{m.name} = {m.value}')
    lines.append('')
    lines.append('// 操作码名 -> 编码 (供 UCBC 编码器使用)')
    lines.append('var opcodeByName = map[string]uint8{')
    for m in Opcode:
        lines.append(f'\t"{m.name}": op{m.name},')
    lines.append('}')
    lines.append('')
    lines.append('// SYS 功能号 (与 isa.py Syscall 一致)')
    for s in Syscall:
        lines.append(f'const {sys_id(s.name)} = {s.value}')
    lines.append('')
    return '\n'.join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description='生成/校验 codecin/native/engine/isa_gen.go')
    ap.add_argument('--check', action='store_true', help='仅校验一致')
    args = ap.parse_args()

    targets = [
        (OUT_PATH, build_go(), 'native isa_gen.go'),
        (COMPILER_SYS_PATH, build_compiler_sys(), 'compiler syscalls.go'),
    ]
    if args.check:
        ok = True
        for path, content, label in targets:
            if os.path.exists(path):
                with open(path, 'r', encoding='utf-8') as f:
                    if f.read() == content:
                        print(f'{label} up to date.')
                        continue
                print(f'{label} OUT OF DATE: run `python script/gen_native_isa.py`')
            else:
                print(f'{label} missing: run `python script/gen_native_isa.py`')
            ok = False
        return 0 if ok else 1

    for path, content, label in targets:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f'Written {path}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
